sudo: false
language: php

cache:
    directories:
        - $HOME/.composer/cache/files
env:
    - SYMFONY_VERSION=4.4.*

php:
  - 7.2
  - 7.3
  - 7.4


matrix:
    include:
        - php: 7.4
          env: SYMFONY_VERSION=3.4.*
        - php: 7.4
          env: SYMFONY_VERSION=4.3.*
        - php: 7.4
          env: SYMFONY_VERSION=5.0.*
        - php: 8.0
          env: SYMFONY_VERSION=5.2.*


install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/form:${SYMFONY_VERSION} --no-update
  - composer update

script:
  - vendor/bin/phpunit
