services:
    settings_manager:
      alias: dmishh.settings.settings_manager

    dmishh.settings.settings_manager:
        class: Dmishh\Bundle\SettingsBundle\Manager\SettingsManager
        arguments:
            - @doctrine.orm.entity_manager
            - @dmishh.settings.serializer
            - %settings_manager.settings%

    dmishh.settings.cached_settings_manager:
        class: Dmishh\Bundle\SettingsBundle\Manager\CachedSettingsManager
        arguments: [@dmishh.settings.settings_manager, %dmishh.settings.cache.lifetime%]

    dmishh.settings.serializer_factory:
        class: Dmishh\Bundle\SettingsBundle\Serializer\SerializerFactory

    dmishh.settings.serializer:
        class: Dmishh\Bundle\SettingsBundle\Serializer\SerializerInterface
        factory_service: dmishh.settings.serializer_factory
        factory_method: create
        arguments: [%settings_manager.serialization%]

    form.type.settings_management:
        class: Dmishh\Bundle\SettingsBundle\Form\Type\SettingsType
        arguments:
            - %settings_manager.settings%
        tags:
            - { name: form.type, alias: settings_management }
